apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-video-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-video-api
  template:
    metadata:
      labels:
        app: dog-video-api
    spec:
      hostname: dog-video-api
      serviceAccountName: dog-service-account
      containers:
      - name: dog-video-api
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/dog-video-api:latest
        resources:
          requests:
            cpu: 100m
            memory: "1024Mi"
          limits:
            cpu: 1000m
            memory: "2048Mi"
        ports:
        - containerPort: 3000
        env:
        - name: DOG_VIDEO_API
          value: 'http://dog-video-api.default.svc.cluster.local:80'
        - name: AWS_REGION
          value: "us-east-1"   
        - name: VIDEO_QUEUE
          value: "video-queue"