apiVersion: v1
kind: Service
metadata:
  name: dog-video-lb
  namespace: default
spec:
  selector:
    app: dog-video
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer